staticscanners/clair/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.conf.urls import url
from staticscanners.clair import views

app_name = 'clair'

urlpatterns = [
    # Bandit scan list

    url(r'^clair_list',
        views.clair_list,
        name='clair_list'),

    url(r'^clair_all_vuln',
        views.list_vuln,
        name='clair_all_vuln'),

    url(r'^clair_vuln_data',
        views.clair_vuln_data,
        name='clair_vuln_data'),

    url(r'^clair_details',
        views.clair_details,
        name='clair_details'),

    url(r'^del_clair',
        views.del_clair,
        name='del_clair'),

    url(r'^clair_del_vuln',
        views.clair_del_vuln,
        name='clair_del_vuln'),
    url(r'^export',
        views.export,
        name='export'),
]

staticscanners/dependencycheck/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.conf.urls import url
from staticscanners.dependencycheck import views

app_name = 'dependencycheck'

urlpatterns = [
    # Bandit scan list
    url(r'^dependencycheck_list',
        views.dependencycheck_list,
        name='dependencycheck_list'),

    url(r'^dependencycheck_all_vuln',
        views.list_vuln,
        name='dependencycheck_all_vuln'),

    url(r'^dependencycheck_vuln_data',
        views.dependencycheck_vuln_data,
        name='dependencycheck_vuln_data'),

    url(r'^dependencycheck_details',
        views.dependencycheck_details,
        name='dependencycheck_details'),

    url(r'^del_dependencycheck',
        views.del_dependencycheck,
        name='del_dependencycheck'),

    url(r'^dependencycheck_del_vuln',
        views.dependencycheck_del_vuln,
        name='dependencycheck_del_vuln'),
    url(r'^export',
        views.export,
        name='export'),
]

staticscanners/trivy/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.conf.urls import url
from staticscanners.trivy import views

app_name = 'trivy'

urlpatterns = [
    # Bandit scan list

    url(r'^trivy_list',
        views.trivy_list,
        name='trivy_list'),

    url(r'^trivy_all_vuln',
        views.list_vuln,
        name='trivy_all_vuln'),

    url(r'^trivy_vuln_data',
        views.trivy_vuln_data,
        name='trivy_vuln_data'),

    url(r'^trivy_details',
        views.trivy_details,
        name='trivy_details'),

    url(r'^del_trivy',
        views.del_trivy,
        name='del_trivy'),

    url(r'^trivy_del_vuln',
        views.trivy_del_vuln,
        name='trivy_del_vuln'),
    url(r'^export',
        views.export,
        name='export'),
]

staticscanners/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.conf.urls import url
from staticscanners import views

app_name = 'staticscanners'

urlpatterns = [
    url(r'^report_import/',
        views.report_import,
        name='report_import'),
]

tools/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.conf.urls import url
from tools import views

app_name = 'tools'

urlpatterns = [
    url(r'^sslscan/$',
        views.sslscan,
        name='sslscan'),
    url(r'^sslscan_result/$',
        views.sslscan_result,
        name='sslscan_result'),
    url(r'^sslcan_del/$',
        views.sslcan_del,
        name='sslcan_del'),

    # Nikto requests
    url(r'^nikto/$',
        views.nikto,
        name='nikto'),
    url(r'^nikto_result/$',
        views.nikto_result,
        name='nikto_result'),
    url(r'^nikto_scan_del/$',
        views.nikto_scan_del,
        name='nikto_scan_del'),

    url(r'^nikto_result_vul/$',
        views.nikto_result_vul,
        name='nikto_result_vul'),
    url(r'^nikto_vuln_del/$',
        views.nikto_vuln_del,
        name='nikto_vuln_del'),

    # nmap requests
    url(r'^nmap_scan/$',
        views.nmap_scan,
        name='nmap_scan'),
    url(r'^nmap/$',
        views.nmap,
        name='nmap'),
    url(r'^nmap_result/$',
        views.nmap_result,
        name='nmap_result'),
    url(r'^nmap_scan_del/$',
        views.nmap_scan_del,
        name='nmap_scan_del'),

    #Nmap_Vulners
    url(r'^nmap_vulners_scan/$',
        views.nmap_vulners_scan,
        name='nmap_scan'),
    url(r'^nmap_vulners/$',
        views.nmap_vulners,
        name='nmap_vulners'),
    url(r'^nmap_vulners_port_list/$',
        views.nmap_vulners_port,
        name='nmap_vulners_port'),
]

webscanners/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.conf.urls import url
from webscanners import web_views

app_name = 'webscanners'

urlpatterns = [
    url(r'^login/$',
        web_views.login,
        name='login'),
    url(r'^signup/$',
        web_views.signup,
        name='signup'),
    url(r'^auth/$',
        web_views.auth_view,
        name='auth'),
    url(r'^logout/$',
        web_views.logout,
        name='logout'),
    url(r'^loggedin/$',
        web_views.loggedin,
        name='loggedin'),
    url(r'^$',
        web_views.index,
        name='index'),
    url(r'^setting/',
        web_views.setting,
        name='setting'),


    # Burp scans
    url(r'^xml_upload',
        web_views.xml_upload,
        name='xml_upload'),
    url(r'^email_setting',
        web_views.email_setting,
        name='email_setting', ),
    url(r'^cookie_add',
        web_views.add_cookies,
        name='cookie_add', ),

    url(r'^web_task_launch',
        web_views.web_task_launch,
        name='web_task_launch'),

    url(r'^web_scan_schedule',
        web_views.web_scan_schedule,
        name='web_scan_schedule'),

    url(r'^del_web_scan_schedule',
        web_views.del_web_scan_schedule,
        name='del_web_scan_schedule'),

    url(r'^sel_login',
        web_views.sel_login,
        name='sel'),

    url(r'save_cookie',
        web_views.save_cookie,
        name='save_cookie'),

    url(r'exclude_url',
        web_views.exclude_url,
        name='exclude_url'),

    url(r'^cookies_list',
        web_views.cookies_list,
        name='cookies_list'),

    url(r'^cookies_del',
        web_views.del_cookies,
        name='cookies_del'),

    url(r'^excluded_url_list',
        web_views.exluded_url_list,
        name='excluded_url_list'),

    url(r'^del_notify',
        web_views.del_notify,
        name='del_notify'),


    url(r'^del_all_notify',
        web_views.del_all_notify,
        name='del_all_notify'),

]

staticscanners/banditscanner/views.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.shortcuts import render, render_to_response, HttpResponse, HttpResponseRedirect
from staticscanners.models import bandit_scan_results_db, bandit_scan_db
import hashlib
from django.urls import reverse
from jiraticketing.models import jirasetting


def banditscans_list(request):
    """
    Bandit Scan list.
    :param request:
    :return:
    """
    all_bandit_scan = bandit_scan_db.objects.all()

    return render(request, 'banditscanner/banditscans_list.html',
                  {'all_bandit_scan': all_bandit_scan})


def banditscan_list_vuln(request):
    """
    Vulnerability list.
    :param request:
    :return:
    """
    jira_url = ''
    jira = jirasetting.objects.all()
    for d in jira:
        jira_url = d.jira_server

    if request.method == 'GET':
        scan_id = request.GET['scan_id']
    else:
        scan_id = None

    bandit_all_vuln = bandit_scan_results_db.objects.filter(
        scan_id=scan_id).values(
        'test_name',
        'issue_severity',
        'scan_id',
        'vul_col',
    ).distinct()

    return render(request, 'banditscanner/banditscan_list_vuln.html',
                  {'bandit_all_vuln': bandit_all_vuln,
                   'jira_url': jira_url
                   })


def banditscan_vuln_data(request):
    """
    :param request:
    :return:
    """
    jira_url = ''
    jira = jirasetting.objects.all()
    for d in jira:
        jira_url = d.jira_server

    if request.method == 'GET':
        scan_id = request.GET['scan_id']
        test_name = request.GET['test_name']
    else:
        scan_id = None
        test_name = None

    if request.method == "POST":
        false_positive = request.POST.get('false')
        status = request.POST.get('status')
        vuln_id = request.POST.get('vuln_id')
        scan_id = request.POST.get('scan_id')
        vuln_name = request.POST.get('vuln_name')
        bandit_scan_results_db.objects.filter(vuln_id=vuln_id,
                                              scan_id=scan_id).update(false_positive=false_positive,
                                                                      vuln_status=status)

        if false_positive == 'Yes':
            vuln_info = bandit_scan_results_db.objects.filter(scan_id=scan_id, vuln_id=vuln_id)
            for vi in vuln_info:
                name = vi.test_name
                filename = vi.filename
                Severity = vi.issue_severity
                dup_data = name + filename + Severity
                false_positive_hash = hashlib.sha256(dup_data.encode('utf-8')).hexdigest()
                bandit_scan_results_db.objects.filter(vuln_id=vuln_id,
                                                      scan_id=scan_id).update(false_positive=false_positive,
                                                                              vuln_status=status,
                                                                              false_positive_hash=false_positive_hash
                                                                              )

            all_bandit_data = bandit_scan_results_db.objects.filter(scan_id=scan_id, false_positive='No')

            total_vul = len(all_bandit_data)
            total_high = len(all_bandit_data.filter(issue_severity="HIGH"))
            total_medium = len(all_bandit_data.filter(issue_severity="MEDIUM"))
            total_low = len(all_bandit_data.filter(issue_severity="LOW"))
            total_duplicate = len(all_bandit_data.filter(vuln_duplicate='Yes'))

            bandit_scan_db.objects.filter(scan_id=scan_id).update(
                total_vuln=total_vul,
                SEVERITY_HIGH=total_high,
                SEVERITY_MEDIUM=total_medium,
                SEVERITY_LOW=total_low,
                total_dup=total_duplicate
            )

        return HttpResponseRedirect(
            reverse('banditscanner:banditscan_vuln_data') + '?scan_id=%s&test_name=%s' % (scan_id, vuln_name))

    bandit_vuln_data = bandit_scan_results_db.objects.filter(scan_id=scan_id,
                                                             test_name=test_name,
                                                             vuln_status='Open',
                                                             false_positive='No')
    vuln_data_closed = bandit_scan_results_db.objects.filter(scan_id=scan_id,
                                                             test_name=test_name,
                                                             vuln_status='Closed',
                                                             false_positive='No')
    false_data = bandit_scan_results_db.objects.filter(scan_id=scan_id,
                                                       test_name=test_name,
                                                       false_positive='Yes')

    return render(request, 'banditscanner/banditscan_vuln_data.html',
                  {'bandit_vuln_data': bandit_vuln_data,
                   'false_data': false_data,
                   'vuln_data_closed': vuln_data_closed,
                   'jira_url': jira_url
                   })


def banditscan_details(request):
    """

    :param request:
    :return:
    """
    jira_url = ''
    jira = jirasetting.objects.all()
    for d in jira:
        jira_url = d.jira_server

    if request.method == 'GET':
        scan_id = request.GET['scan_id']
        vuln_id = request.GET['vuln_id']
    else:
        scan_id = None
        vuln_id = None

    bandit_vuln_details = bandit_scan_results_db.objects.filter(
        scan_id=scan_id,
        vuln_id=vuln_id
    )

    return render(request, 'banditscanner/bandit_vuln_details.html',
                  {'bandit_vuln_details': bandit_vuln_details}
                  )


def del_bandit_scan(request):
    """
    Delete Bandit Scans.
    :param request:
    :return:
    """
    if request.method == 'POST':
        scan_id = request.POST.get("scan_id")
        scan_item = str(scan_id)
        value = scan_item.replace(" ", "")
        value_split = value.split(',')
        split_length = value_split.__len__()
        # print "split_length", split_length
        for i in range(0, split_length):
            scan_id = value_split.__getitem__(i)
            item = bandit_scan_db.objects.filter(scan_id=scan_id)
            item.delete()
            item_results = bandit_scan_results_db.objects.filter(scan_id=scan_id)
            item_results.delete()
        return HttpResponseRedirect(reverse('banditscanner:banditscans_list'))


def bandit_del_vuln(request):
    """
    The function Delete the bandit Vulnerability.
    :param request:
    :return:
    """
    if request.method == 'POST':
        vuln_id = request.POST.get("del_vuln", )
        un_scanid = request.POST.get("scan_id", )
        scan_item = str(vuln_id)
        value = scan_item.replace(" ", "")
        value_split = value.split(',')
        split_length = value_split.__len__()
        # print "split_length", split_length
        for i in range(0, split_length):
            vuln_id = value_split.__getitem__(i)
            delete_vuln = bandit_scan_results_db.objects.filter(vuln_id=vuln_id)
            delete_vuln.delete()
        all_bandit_data = bandit_scan_results_db.objects.filter(scan_id=un_scanid)

        total_vul = len(all_bandit_data)
        total_high = len(all_bandit_data.filter(issue_severity="HIGH"))
        total_medium = len(all_bandit_data.filter(issue_severity="MEDIUM"))
        total_low = len(all_bandit_data.filter(issue_severity="LOW"))

        bandit_scan_db.objects.filter(scan_id=un_scanid).update(
            total_vuln=total_vul,
            SEVERITY_HIGH=total_high,
            SEVERITY_MEDIUM=total_medium,
            SEVERITY_LOW=total_low
        )

        return HttpResponseRedirect(reverse('banditscanner:banditscan_list_vuln/') + '?scan_id=%s' % un_scanid)

staticscanners/templates/dependencycheck/dependencycheckscan_list_vuln.html
{% extends 'dashboard/base.html' %}

{% block body %}
<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <br>
                        <div class="d-md-flex align-items-center">
                            <h1 class="card-title">Vulnerability List</h1>
                        </div>
                        <br>
                        <div class="row">
                            <div class="table-responsive">
                                <table id="dependencycheck_scans_list" class="table table-bordered data-table table-fixed" width="100%">
                            <thead>
                            <tr>
                                <th>Vulnerability</th>
                                <th>Risk</th>
                            </tr>
                            </thead>
                            <tbody>{% for data in dependencycheck_all_vuln %}
                            <tr data-target="#">
                                <td>
                                    <a href="{% url 'dependencycheck:dependencycheck_vuln_data' %}?scan_id={{data.scan_id}}&test_name={{data.name}}">{{data.name}}</a>
                                </td>
                                <td><span class="badge badge-pill badge-{{data.vul_col}}">{{data.severity}}</span></td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

staticscanners/templates/dependencycheck/dependencycheckscans_list.html
{% extends 'dashboard/base.html' %}

{% block body %}

<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script type="text/javascript">

    $("#checkAll").change(function () {
        $("input:checkbox").prop('checked', $(this).prop("checked"));
    });
    $(document).ready(function() {
        $("button").click(function(){
            var scan_id = ['a7af5b68-b661-45ad-90fd-ffa27526cdce'];
            $.each($("input[name='del_scan_id']:checked"), function(){
                scan_id.push($(this).val());
            });

            var json_scanid = scan_id.join(", ");
            $.ajax({
                type:'POST',
                <!--contentType: 'application/json; charset=utf-8',-->
                url:'{% url 'dependencycheck:del_dependencycheck' %}',
                data:{
                   scan_id: json_scanid,
                   csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                },
                sucess:function(){

                }
            });
            setTimeout(location.reload(), 6000);
        });

    });


</script>


<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="float-right">
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a href="{% url 'webscanners:xml_upload' %}" class="btn btn-primary btn-mini"><i
                                        class="icon-upload-alt"></i> Upload XML</a>
                            </div>
                            <button type="button" class="btn btn-danger btn-mini" onclick="">Delete Selected</button>
                        </div>
                        <br>
                        <br>
                        <div class="float-right">
                            <form action="{% url 'dependencycheck:export' %}" method="post"
                                  class="forms-sample">
                                {% csrf_token %}
                                <div class="form-row align-items-center">
                                    <div class="col-auto my-1">
                                        <select name="type" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                                            <option value="csv" selected>CSV</option>
                                            <option value="json">JSON</option>
                                            <option value="yaml">YAML</option>
                                        </select>
                                    </div>
                                    <div class="col-auto my-1">
                                        <input type="hidden" name="scan_id"
                                               value="{% for data in all_dependencycheck_scan %}{{data.scan_id}}{% endfor %}"/>
                                        <button type="submit" class="btn btn-primary"><i
                                                class="fas fa-arrow-alt-circle-down"></i></button>
                                    </div>
                                </div>
                            </form>

                        </div>
                        <br>
                        <div class="d-md-flex align-items-center">
                            <h1 class="card-title">Dependency Check Scan List</h1>
                        </div>
                        <br>
                        <div class="row">
                            <div class="table-responsive">
                                <table id="dependencycheck_scans_list" class="table table-bordered data-table">
                                    <thead>
                                    <tr>
                                        <th><label class="customcheckbox m-b-20">
                                            <input type="checkbox" id="mainCheckbox">
                                            <span class="checkmark"></span>
                                        </label></th>
                                        <th>Project Name</th>
                                        <th>Status</th>
                                        <th>Date Time</th>
                                        <th>Total Vulnerability</th>
                                        <th>HIGH</th>
                                        <th>MEDIUM</th>
                                        <th>LOW</th>
                                        <th>Duplicates</th>
                                        <!--<th>Export</th>-->
                                        <!--<th></th>-->
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>{% for data in all_dependencycheck_scan %}
                                    <tr data-target="#">
                                        <td>
                                            <form>
                                                <label class="customcheckbox">
                                                    <input type="checkbox" class="listCheckbox"
                                                           value="{{data.scan_id}}"
                                                           name="del_scan_id"
                                                           onClick="reload">
                                                    <span class="checkmark"></span>
                                                </label>
                                            </form>
                                        </td>
                                        <td>
                                            <a href="{% url 'dependencycheck:dependencycheck_all_vuln' %}?scan_id={{data.scan_id}}">{{data.project_name}}</a>
                                        </td>
                                        <td width="20%">
                                            <div>
                                                <div class="d-flex no-block align-items-center">
                                                    <span>{{data.scan_status}}{{data.vul_status}}% Completed</span>
                                                </div>
                                                <div class="progress{% if data.scan_status != '100.0' %} active progress-striped{% endif %}">
                                                    <div class="progress-bar progress-bar-striped" role="progressbar"
                                                         style="width: {{data.scan_status}}{{data.vul_status}}%" aria-valuenow="10" aria-valuemin="0"
                                                         aria-valuemax="100"></div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>{{data.date_time}}</td>
                                        <td><span class="badge badge-pill badge-dark">{{data.total_vuln}}</span></td>
                                        <td><span class="badge badge-pill badge-danger">{{data.SEVERITY_HIGH}}</span>
                                        </td>
                                        <td><span class="badge badge-pill badge-warning">{{data.SEVERITY_MEDIUM}}</span>
                                        </td>
                                        <td><span class="badge badge-pill badge-info">{{data.SEVERITY_LOW}}</span></td>
                                        <td><span class="badge badge-pill badge-secondary">{{data.total_dup}}</span>
                                        </td>
                                        <td>
                                            <form action="{% url 'dependencycheck:del_dependencycheck' %}" method="post"
                                                  class="forms-sample">
                                                {% csrf_token %}
                                                <input type="hidden" name="scan_id" value="{{data.scan_id}}"/>
                                                <!--<input type="hidden" name="scan_url" value="{{data.scan_url}}"/>-->
                                                <button class="btn btn-danger btn-mini"><i class="fas fa-trash"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}