tools/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.conf.urls import url
from tools import views

app_name = 'tools'

urlpatterns = [
    url(r'^sslscan/$',
        views.sslscan,
        name='sslscan'),
    url(r'^sslscan_result/$',
        views.sslscan_result,
        name='sslscan_result'),
    url(r'^sslcan_del/$',
        views.sslcan_del,
        name='sslcan_del'),

    # Nikto requests
    url(r'^nikto/$',
        views.nikto,
        name='nikto'),
    url(r'^nikto_result/$',
        views.nikto_result,
        name='nikto_result'),
    url(r'^nikto_scan_del/$',
        views.nikto_scan_del,
        name='nikto_scan_del'),

    url(r'^nikto_result_vul/$',
        views.nikto_result_vul,
        name='nikto_result_vul'),
    url(r'^nikto_vuln_del/$',
        views.nikto_vuln_del,
        name='nikto_vuln_del'),

    # nmap requests
    url(r'^nmap_scan/$',
        views.nmap_scan,
        name='nmap_scan'),
    url(r'^nmap/$',
        views.nmap,
        name='nmap'),
    url(r'^nmap_result/$',
        views.nmap_result,
        name='nmap_result'),
    url(r'^nmap_scan_del/$',
        views.nmap_scan_del,
        name='nmap_scan_del'),

    #Nmap_Vulners
    url(r'^nmap_vulners_scan/$',
        views.nmap_vulners_scan,
        name='nmap_scan'),
    url(r'^nmap_vulners/$',
        views.nmap_vulners,
        name='nmap_vulners'),
    url(r'^nmap_vulners_port_list/$',
        views.nmap_vulners_port,
        name='nmap_vulners_port'),
]

webscanners/burpscanner/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.conf.urls import url
from webscanners.burpscanner import views

app_name = 'burpscanner'

urlpatterns = [
    # Burp scans
    url(r'^burp_launch_scan',
        views.burp_scan_launch,
        name='burp_launch_scan'),

    url(r'^burp_scan_list',
        views.burp_scan_list,
        name='burp_scan_list'),

    url(r'^burp_vuln_list',
        views.burp_list_vuln,
        name='burp_vuln_list'),

    url(r'^burp_vuln_data',
        views.burp_vuln_data,
        name='burp_vuln_data'),

    url(r'^burp_vuln_out',
        views.burp_vuln_out,
        name='burp_vuln_out'),

    url(r'^del_burp_scan',
        views.del_burp_scan,
        name='del_burp_scan'),

    url(r'^del_burp_vuln',
        views.del_burp_vuln,
        name='del_burp_vuln'),

    url(r'^export',
        views.export,
        name='export'),

    url(r'^burp_setting',
        views.burp_setting,
        name='burp_setting'),

]

webscanners/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.conf.urls import url
from webscanners import web_views

app_name = 'webscanners'

urlpatterns = [
    url(r'^login/$',
        web_views.login,
        name='login'),
    url(r'^signup/$',
        web_views.signup,
        name='signup'),
    url(r'^auth/$',
        web_views.auth_view,
        name='auth'),
    url(r'^logout/$',
        web_views.logout,
        name='logout'),
    url(r'^loggedin/$',
        web_views.loggedin,
        name='loggedin'),
    url(r'^$',
        web_views.index,
        name='index'),
    url(r'^setting/',
        web_views.setting,
        name='setting'),


    # Burp scans
    url(r'^xml_upload',
        web_views.xml_upload,
        name='xml_upload'),
    url(r'^email_setting',
        web_views.email_setting,
        name='email_setting', ),
    url(r'^cookie_add',
        web_views.add_cookies,
        name='cookie_add', ),

    url(r'^web_task_launch',
        web_views.web_task_launch,
        name='web_task_launch'),

    url(r'^web_scan_schedule',
        web_views.web_scan_schedule,
        name='web_scan_schedule'),

    url(r'^del_web_scan_schedule',
        web_views.del_web_scan_schedule,
        name='del_web_scan_schedule'),

    url(r'^sel_login',
        web_views.sel_login,
        name='sel'),

    url(r'save_cookie',
        web_views.save_cookie,
        name='save_cookie'),

    url(r'exclude_url',
        web_views.exclude_url,
        name='exclude_url'),

    url(r'^cookies_list',
        web_views.cookies_list,
        name='cookies_list'),

    url(r'^cookies_del',
        web_views.del_cookies,
        name='cookies_del'),

    url(r'^excluded_url_list',
        web_views.exluded_url_list,
        name='excluded_url_list'),

    url(r'^del_notify',
        web_views.del_notify,
        name='del_notify'),


    url(r'^del_all_notify',
        web_views.del_all_notify,
        name='del_all_notify'),

]

webscanners/zapscanner/urls.py
# -*- coding: utf-8 -*-
#                    _
#     /\            | |
#    /  \   _ __ ___| |__   ___ _ __ _   _
#   / /\ \ | '__/ __| '_ \ / _ \ '__| | | |
#  / ____ \| | | (__| | | |  __/ |  | |_| |
# /_/    \_\_|  \___|_| |_|\___|_|   \__, |
#                                     __/ |
#                                    |___/
# Copyright (C) 2017 Anand Tiwari
#
# Email:   anandtiwarics@gmail.com
# Twitter: @anandtiwarics
#
# This file is part of ArcherySec Project.

from django.conf.urls import url
from webscanners.zapscanner import views

app_name = 'zapscanner'

urlpatterns = [

    url(r'^zap_scan/',
        views.zap_scan,
        name='zap_scan'),

    url(r'^zap_scan_list/',
        views.zap_scan_list,
        name='zap_scan_list'),

    url(r'^zap_list_vuln/',
        views.zap_list_vuln,
        name='zap_list_vuln'),

    url(r'^zap_vuln_details/',
        views.zap_vuln_details,
        name='zap_vuln_details'),

    url(r'^zap_settings/',
        views.zap_settings,
        name='zap_settings'),

    url(r'^zap_setting_update/',
        views.zap_setting_update,
        name='zap_setting_update'),

    url(r'^del_zap_scan',
        views.del_zap_scan,
        name='del_zap_scan'),

    url(r'^del_zap_vuln',
        views.del_zap_vuln,
        name='del_zap_vuln'),

    url(r'^zap_vuln_check',
        views.zap_vuln_check,
        name='zap_vuln_check'),

    url(r'^sel_login',
        views.sel_login,
        name='sel_login'),

    url(r'save_cookie',
        views.save_cookie,
        name='save_cookie'),

    url(r'exclude_url',
        views.exclude_url,
        name='exclude_url'),

    url(r'^zap_scan_pdf_gen',
        views.zap_scan_pdf_gen,
        name='zap_scan_pdf_gen'),

    url(r'^zap_rescan',
        views.zap_rescan,
        name='zap_rescan'),

    url(r'^cookies_list',
        views.cookies_list,
        name='cookies_list'),

    url(r'^cookies_del',
        views.del_cookies,
        name='cookies_del'),

    url(r'^excluded_url_list',
        views.exluded_url_list,
        name='excluded_url_list'),

    # url(r'^zap_scan_task_launch',
    #     views.zap_scan_task_launch,
    #     name='zap_scan_task_launch'),

    # url(r'^zap_scan_schedule',
    #     views.zap_scan_schedule,
    #     name='zap_scan_schedule'),
    #
    # url(r'^del_zap_scan_schedule',
    #     views.del_zap_scan_schedule,
    #     name='del_zap_scan_schedule'),

    url(r'^export',
        views.export,
        name='export'),

]

webscanners/templates/burpscanner/burp_list_vuln.html
{% extends 'dashboard/base.html' %}

{% block body %}
<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <br>
                        <div class="d-md-flex align-items-center">
                            <h1 class="card-title">Vulnerability List</h1>
                        </div>
                        <br>
                        <div class="row">
                            <div class="table-responsive">
                                <table id="zap_scans_list" class="table table-bordered data-table" width="100%">
                                    <thead>
                                    <tr>

                                        <th>Vulnerability</th>
                                        <th>Risk</th>

                                    </tr>
                                    </thead>
                                    <tbody>{% for data in burp_all_vul %}
                                    <tr data-target="#">
                                        <td>
                                            <a href="{% url 'burpscanner:burp_vuln_out' %}?scan_id={{data.scan_id}}&scan_name={{data.name}}">{{data.name}}</a>
                                        </td>
                                        <td><span class="badge badge-pill badge-{{data.severity_color}}">{{data.severity}}</span>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

webscanners/templates/burpscanner/burp_scan_list.html
{% extends 'dashboard/base.html' %}

{% block body %}


<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script type="text/javascript">

    $("#checkAll").change(function () {
        $("input:checkbox").prop('checked', $(this).prop("checked"));
    });
    $(document).ready(function() {
        $("button").click(function(){
            var scan_id = ['a7af5b68-b661-45ad-90fd-ffa27526cdce'];
            $.each($("input[name='del_scan_id']:checked"), function(){
                scan_id.push($(this).val());
            });

            var json_scanid = scan_id.join(", ");
            $.ajax({
                type:'POST',
                <!--contentType: 'application/json; charset=utf-8',-->
                url:'{% url 'burpscanner:del_burp_scan' %}',
                data:{
                   scan_id: json_scanid,
                   csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                },
                sucess:function(){

                }
            });
            setTimeout(function(){location.reload();},1000);
        });

    });




</script>


<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="float-right">
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a href="{% url 'webscanners:xml_upload' %}" class="btn btn-primary btn-mini"><i
                                        class="icon-upload-alt"></i> Upload XML</a>
                            </div>
                            <button type="button" class="btn btn-danger btn-mini" onclick="">Delete Selected</button>
                        </div>
                        <br>
                        <br>
                        <div class="float-right">
                            <form action="{% url 'burpscanner:export' %}" method="post"
                                  class="forms-sample">
                                {% csrf_token %}
                                <div class="form-row align-items-center">
                                    <div class="col-auto my-1">
                                        <select name="type" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                                            <option value="csv" selected>CSV</option>
                                            <option value="json">JSON</option>
                                            <option value="yaml">YAML</option>
                                        </select>
                                    </div>
                                    <div class="col-auto my-1">
                                        <input type="hidden" name="scan_id"
                                               value="{% for data in all_burp_scan %}{{data.scan_id}}{% endfor %}"/>
                                        <button type="submit" class="btn btn-primary"><i
                                                class="fas fa-arrow-alt-circle-down"></i></button>
                                    </div>
                                </div>
                            </form>

                        </div>
                        <br>
                        <div class="d-md-flex align-items-center">
                            <h1 class="card-title">Burp Scan List</h1>
                        </div>
                        <br>
                        <div class="row">
                            <div class="table-responsive">
                                <table id="burp_scan_list" class="table table-bordered data-table">
                                    <thead>
                                    <tr>
                                        <th><label class="customcheckbox m-b-20">
                                            <input type="checkbox" id="mainCheckbox">
                                            <span class="checkmark"></span>
                                        </label></th>
                                        <th>URL</th>
                                        <th>Status</th>
                                        <!--<th>Date Time</th>-->
                                        <th>Total Vulnerability</th>
                                        <th>High</th>
                                        <th>Medium</th>
                                        <th>Low</th>
                                        <th>Info</th>
                                        <th>Duplicates</th>
                                        <!--<th>Export</th>-->
                                        <!--<th></th>-->
                                    </tr>
                                    </thead>{% for data in all_burp_scan %}
                                    <tbody>
                                    <tr data-target="#">
                                         <td>
                                            <form>
                                                <label class="customcheckbox">
                                                    <input type="checkbox" class="listCheckbox"
                                                           value="{{data.scan_id}}"
                                                           name="del_scan_id"
                                                           onClick="reload">
                                                    <span class="checkmark"></span>
                                                </label>
                                            </form>
                                        </td>
                                        <td>
                                            <a href="{% url 'burpscanner:burp_vuln_list' %}?scan_id={{data.scan_id}}">{{data.url}}</a>
                                        </td>
                                        <td width="20%">
                                            <div>
                                                <div class="d-flex no-block align-items-center">
                                                    <span>{{data.scan_status}}{{data.vul_status}}% Completed</span>
                                                </div>
                                                <div class="progress{% if data.scan_status != '100.0' %} active progress-striped{% endif %}">
                                                    <div class="progress-bar progress-bar-striped" role="progressbar"
                                                         style="width: {{data.scan_status}}{{data.vul_status}}%"
                                                         aria-valuenow="10" aria-valuemin="0"
                                                         aria-valuemax="100"></div>
                                                </div>
                                            </div>
                                        </td>
                                        <!--<td>{{data.date_time}}</td>-->
                                        <td><span class="badge badge-pill badge-dark">{{data.total_vul}}</span></td>
                                        <td><span class="badge badge-pill badge-danger">{{data.high_vul}}</span></td>
                                        <td><span class="badge badge-pill badge-warning">{{data.medium_vul}}</span></td>
                                        <td><span class="badge badge-pill badge-info">{{data.low_vul}}</span></td>
                                        <td><span class="badge badge-pill badge-info">{{data.info_vul}}</span></td>
                                        <td><span class="badge badge-pill badge-secondary">{{data.total_dup}}</span>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

webscanners/templates/burpscanner/burp_setting_form.html
{% extends 'dashboard/base.html' %}

{% block body %}

<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-md-center">
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <div class="d-md-flex align-items-center">
                            <h1 class="card-title">Burp Setting</h1>
                        </div>
                        <br>
                        <div class="card">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card">
                                        <form class="form-horizontal" method="POST" action="{% url 'burpscanner:burp_setting' %}">
                                            {% csrf_token %}
                                            <div class="form-group row">
                                                <label
                                                        class="col-sm-4 col-form-label">Burp API Key</label>
                                                <div class="col-sm-6">
                                                    <small><em>Burp API Key </em></small>
                                                    <input type="text" name="burpapikey" value="{{ burp_api_key }}"
                                                           class="form-control"
                                                    />
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label
                                                        class="col-sm-4 col-form-label">Burp host</label>
                                                <div class="col-sm-6">
                                                    <small><em>Burp API Host (Ex.127.0.0.1)</em></small>
                                                    <input type="text" name="burpath" value="{{ burp_url }}"
                                                           class="form-control"
                                                    />
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label
                                                        class="col-sm-4 col-form-label">Burp API Port</label>
                                                <div class="col-sm-6">
                                                    <small><em>Burp API Port (Ex.8080)</em></small>
                                                    <input type="text" name="burport" value="{{ burp_port }}"
                                                           class="form-control"
                                                    />
                                                </div>
                                            </div>
                                            <div class="form-actions">
                                            <button type="submit" class="btn btn-success">Save</button>
                                        </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

webscanners/templates/burpscanner/burp_vuln_data.html
{% extends 'dashboard/base.html' %}

{% block body %}
{% for data in vuln_data %}
<div class="page-wrapper">
    <div class="container-fluid">
        <div class="float-right">

        </div>
        <div class="row">
            <div class="col-md-12">
                 <div class="col-md-auto">
                    <div class="float-right">
                        <!-- Large modal -->
                         <a href="/jira/submit_jira_ticket/?summary={{data.name}}&description={{data.issueDetail}}%0a%0a%0a Vulnerable URL: {{data.host}} %0a%0a Vulnerable Parameter: {{data.location}} %0a%0a Solution: {{data.remediationBackground}} %0a%0a Archery URL: {SERVERIP}/webscanners/burp_vuln_data/?vuln_id={{data.vuln_id}} %0a%0a Request Header: {{ data.requestHeader }}&scanner=burp&vuln_id={{data.vuln_id}}&scan_id={{data.scan_id}} "
               class="btn btn-primary btn-lg active" role="button" aria-pressed="true"> Create Jira Ticket</a>

                    </div>
                </div>
                <h1>{{data.name}}</h1>
                <br>
                <div class="card">
                    <div class="accordion" id="accordionExample">
                        <div class="card m-b-0">
                            <div class="card-header" id="headingOne">
                                <h5 class="mb-0">
                                    <a data-toggle="collapse" data-target="#collapseOne" aria-expanded="true"
                                       aria-controls="collapseOne">
                                        <i class="m-r-5 fa fa-chevron-down" aria-hidden="true"></i>
                                        <span>Description</span>
                                    </a>
                                </h5>
                            </div>
                            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                                 data-parent="#accordionExample">
                                <div class="card-body">
                                    {{data.description | safe}}
                                </div>
                            </div>
                        </div>
                        <div class="card m-b-0 border-top">
                            <div class="card-header" id="headingTwo">
                                <h5 class="mb-0">
                                    <a class="collapsed" data-toggle="collapse" data-target="#collapseTwo"
                                       aria-expanded="false" aria-controls="collapseTwo">
                                        <i class="m-r-5 fa fa-chevron-down" aria-hidden="true"></i>
                                        <span>Instance</span>
                                    </a>
                                </h5>
                            </div>
                            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo"
                                 data-parent="#accordionExample">
                                <div class="card-body">
                                    <div class="col-md-6">
                                    <table class="table table-bordered data-table table-fixed">
                                        <thead>
                                            <tr>
                                                <td>URL</td>
                                                <td>Path</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>
                                                {{data.request_response_url}}
                                            </td>
                                            <td>
                                                {{data.path}}
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                        </div>
                                </div>
                            </div>
                        </div>
                        <div class="card m-b-0 border-top">
                            <div class="card-header" id="headingThree">
                                <h5 class="mb-0">
                                    <a class="collapsed" data-toggle="collapse" data-target="#collapseThree"
                                       aria-expanded="false" aria-controls="collapseThree">
                                        <i class="m-r-5 fa fa-chevron-down" aria-hidden="true"></i>
                                        <span>Solutions</span>
                                    </a>
                                </h5>
                            </div>
                            <div id="collapseThree" class="collapse" aria-labelledby="headingThree"
                                 data-parent="#accordionExample">
                                <div class="card-body">
                                     {{data.remediation | safe}}
                                </div>
                            </div>
                        </div>
                        <div class="card m-b-0 border-top">
                            <div class="card-header" id="heading4">
                                <h5 class="mb-0">
                                    <a class="collapsed" data-toggle="collapse" data-target="#collapse4"
                                       aria-expanded="false" aria-controls="collapse4">
                                        <i class="m-r-5 fa fa-chevron-down" aria-hidden="true"></i>
                                        <span>Reference</span>
                                    </a>
                                </h5>
                            </div>
                            <div id="collapse4" class="collapse" aria-labelledby="heading4"
                                 data-parent="#accordionExample">
                                <div class="card-body">
                                    {{data.reference | safe}}
                                </div>
                            </div>
                        </div>
                        <div class="card m-b-0 border-top">
                            <div class="card-header" id="heading5">
                                <h5 class="mb-0">
                                    <a class="collapsed" data-toggle="collapse" data-target="#collapse5"
                                       aria-expanded="false" aria-controls="collapse5">
                                        <i class="m-r-5 fa fa-chevron-down" aria-hidden="true"></i>
                                        <span>Vulnerability Classifications</span>
                                    </a>
                                </h5>
                            </div>
                            <div id="collapse5" class="collapse" aria-labelledby="heading5"
                                 data-parent="#accordionExample">
                                <div class="card-body">
                                     {{data.vulnerability_classifications | safe}}
                                </div>
                            </div>
                        </div>
                        <div class="card m-b-0 border-top">
                            <div class="card-header" id="heading6">
                                <h5 class="mb-0">
                                    <a class="collapsed" data-toggle="collapse" data-target="#collapse6"
                                       aria-expanded="false" aria-controls="collapse6">
                                        <i class="m-r-5 fa fa-chevron-down" aria-hidden="true"></i>
                                        <span>Request</span>
                                    </a>
                                </h5>
                            </div>
                            <div id="collapse6" class="collapse" aria-labelledby="heading6"
                                 data-parent="#accordionExample">
                                <div class="card-body">
                                    <pre>{{data.request_response_request_data }}</pre>
                                </div>
                            </div>
                        </div>
                        <div class="card m-b-0 border-top">
                            <div class="card-header" id="heading7">
                                <h5 class="mb-0">
                                    <a class="collapsed" data-toggle="collapse" data-target="#collapse7"
                                       aria-expanded="false" aria-controls="collapse7">
                                        <i class="m-r-5 fa fa-chevron-down" aria-hidden="true"></i>
                                        <span>Response</span>
                                    </a>
                                </h5>
                            </div>
                            <div id="collapse7" class="collapse" aria-labelledby="heading7"
                                 data-parent="#accordionExample">
                                <div class="card-body">
                                     <pre>{{data.request_response_response_data }}</pre>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}